FROM node:stretch as build
RUN npm install -g pkg pkg-fetch
ENV NODE node8
ENV PLATFORM alpine
ENV ARCH x64
RUN pkg-fetch ${NODE} ${PLATFORM} ${ARCH}
COPY . .
RUN pkg --debug --targets ${NODE}-${PLATFORM}-${ARCH} --output /runme index.js

FROM alpine:3.10
RUN apk add --no-cache libstdc++
COPY --from=build /runme /runme
CMD ["/runme"]
